### ISSUE TITLE
Game server won't run

### ISSUE THREAD

**Issue by MikeCedonis** [fpiesche/docker-hercules#13]
I'm trying to get this running on my Synology NAS from the docker registry and once I launch it the container stops.
Checking the logs I get this;
</head>
<body>
<h2>hercules_game_servers_1</h2>
<table>
<tr><th>date</th><th>stream</th><th>content</th></tr>
<tr><td>2022-06-01&nbsp;13:26:24</td><td>stdout</td><td>Now&nbsp;Started&nbsp;Athena.
</td></tr>
<tr><td>2022-06-01&nbsp;13:26:24</td><td>stdout</td><td>Looks&nbsp;good,&nbsp;a&nbsp;nice&nbsp;Athena!
</td></tr>
<tr><td>2022-06-01&nbsp;13:26:24</td><td>stdout</td><td>Check&nbsp;complete.
</td></tr>
<tr><td>2022-06-01&nbsp;13:26:24</td><td>stdout</td><td>checking...
</td></tr>
<tr><td>2022-06-01&nbsp;13:26:24</td><td>stdout</td><td>
</td></tr>
<tr><td>2022-06-01&nbsp;13:26:24</td><td>stdout</td><td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;modified&nbsp;by&nbsp;shazeya@syafi.com
</td></tr>
<tr><td>2022-06-01&nbsp;13:26:24</td><td>stdout</td><td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(c)&nbsp;2003&nbsp;Athena&nbsp;Project
</td></tr>
<tr><td>2022-06-01&nbsp;13:26:24</td><td>stdout</td><td>Athena&nbsp;Starting...
</td></tr>
<tr><td>2022-06-01&nbsp;13:26:23</td><td>stdout</td><td>No&nbsp;server&nbsp;executable&nbsp;specified,&nbsp;starting&nbsp;all&nbsp;servers&nbsp;using&nbsp;athena-start...
</td></tr>
<tr><td>2022-06-01&nbsp;13:26:23</td><td>stdout</td><td>Filling&nbsp;server&nbsp;info&nbsp;in&nbsp;/hercules/conf/import/map-server.conf
</td></tr>
<tr><td>2022-06-01&nbsp;13:26:23</td><td>stdout</td><td>Filling&nbsp;server&nbsp;info&nbsp;in&nbsp;/hercules/conf/import/char-server.conf
</td></tr>
<tr><td>2022-06-01&nbsp;13:26:23</td><td>stdout</td><td>Filling&nbsp;database&nbsp;connection&nbsp;info&nbsp;in&nbsp;/hercules/conf/global/sql_connection.conf
</td></tr>
</table></body></html>

If I run the compose I get two containers. The DB is running fine but the game server still cuts off with the same log as above.

![Screenshot_20220601-093010_Chrome](https://user-images.githubusercontent.com/45634750/171417377-61f2d528-e5d6-4c82-bc71-6a43a447ac95.jpg)

Any help would be appreciated and thank you!

**Comment by fpiesche** [comment]
I'm still fairly heavily developing this on the deployment side of things so I've not been able to test this very well yet; I'll try and put some time into investigating this over the weekend. It is getting to the point where it's handed over to the game servers so I'm surprised there's nothing from them in the log files...

**Comment by fpiesche** [comment]
Those files are indeed meant to be missing - I did a bunch of work when I first set up Docker builds here to figure out which of the files and folders are unnecessary and only copy the required ones into the Docker image, in order to keep the size of the images small.

For reference, the official Hercules repository itself, with no compiled servers or anything, is just shy of 89MB; the full images here (depending on architecture) are between 65MB and 70MB *including* the ~30MB base Debian image ;)

Running the servers directly from a manually started Docker container looks to work fine; I suspect the problem is with how the official `start-athena` script runs the three servers in parallel versus how Docker expects applications in a container to behave. I'm testing out a fix as we speak :)

**Comment by fpiesche** [comment]
(for further reference: this wasn't a problem with my previous versions of the Hercules Docker images because I included a Python tool that would manage the servers and that was what the old images were running. However, getting Python into a Docker image alone will inflate the image to 250-300MB so I've moved away from this.

**Comment by fpiesche** [comment]
This isn't an ideal solution, but it should do the job for now. Crucially this fix will actually _stop the container from exiting_ if one or several of the servers crash or exit, and it has turned up a (pre-existing) issue  (#14) whereby it isn't possible to use non-default inter-server username/password. I'll be working on that one next.

Having something that'll allow running all three servers in one container, get all of their logs outputting to `stdout` so Docker can display them to users, *and* exit if one or several of the servers do is a bit of a bigger job; I'll probably need to write some kind of wrapper program that replicates the functionality of `start-athena.sh` without having Docker just exit the container once they're all started as background tasks and the script returns to shell.

**Comment by MikeCedonis** [comment]
Thank you for all the effort!
~~I made it to step 13 on building the Dockerfile
Step 13/24 : RUN ${WORKSPACE}/create-env-file.sh   && ${WORKSPACE}/configure-build.sh   && cd ${HERCULES_SRC} && make   && cd ${WORKSPACE}   && ${WORKSPACE}/assemble-distribution.sh   && ${WORKSPACE}/create-version-file.sh
 ---> Running in e7bd5175bf19
sed: can't read /home/builduser/hercules/src/common/mmo.h: No such file or directory
=== Patching ARM version detection to make armv6 builds work
sed: can't read /home/builduser/hercules/src/common/atomic.h: No such file or directory
/home/builduser/configure-build.sh: line 9: ./configure: No such file or directory
Any clue on the issue?
Going to see if I can dig around the files.~~
I was missing the hercules source 😅

**Comment by fpiesche** [comment]
You shouldn't actually need to rebuild the Docker image - if you get your NAS to pull the same Docker image again it should get the new build which was created and pushed when I merged the pull request (https://github.com/fpiesche/docker-hercules/runs/6734458310)

**Comment by MikeCedonis** [comment]
Sorry when I checked it wasn't updated and sorry again for being a pita but I'm getting this now:
[Debug]: at inter.c:941
2022-06-05 01:46:47	stdout	[1;35m[SQL][0m: Unknown MySQL server host 'db' (-2)
2022-06-05 01:46:47	stdout	[1;37m[Info][0m: Connecting to the Map DB Server....
2022-06-05 01:46:47	stdout	[1;37m[Info][0m: Logging commands to table 'atcommandlog'.
2022-06-05 01:46:47	stdout	[1;37m[Info][0m: Logging chat to table 'chatlog'.
2022-06-05 01:46:47	stdout	[1;37m[Info][0m: Logging item transactions to table 'picklog'.

Time starts from the bottom. Sorry again.
